name: Check
on:
  pull_request:
  push:
    branches:
    - '**'
    - '!l10n/*'

jobs:
  build:
    strategy:
      matrix:
        java: [ 21-jdk ]
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - run: ./gradlew runDatagen --stacktrace
      - run: ./gradlew build --stacktrace -x runDatagen

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/